name: CI - Cristal (Basic Check)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  security-and-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour SonarCloud

      # Scan des vulnérabilités Maven (Backend)
      - name: Snyk Backend Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
        with:
          args: --file=cristal/api/pom.xml

      # Scan des vulnérabilités NPM (Frontend)
      - name: Snyk Frontend Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
        with:
          args: cristal/front

  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify repository structure
        run: |
          echo "Repository successfully checked out"
          ls -la

      - name: CI Success
        run: echo "GitHub Actions is working correctly"
